#!/usr/bin/env bash
# Configure a new Nginx server so that /redirect_me is redirecting to another page with a 301 Moved Permanently

# Update packages and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Create a simple HTML file
echo "Hello World" | sudo tee /var/www/html/index.html

# Configure Nginx for the redirection
sudo bash -c 'cat > /etc/nginx/sites-available/default << EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF'

# Restart Nginx to apply changes
sudo service nginx restart
