#!/usr/bin/env bash
# Configure Nginx server with custom 404 page

# Update packages and install Nginx
apt-get -y update
apt-get -y install nginx

# Create a simple HTML file for the default page
echo "Hello World!" > /var/www/html/index.html

# Create a custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure Nginx
cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

# Restart Nginx to apply changes
service nginx restart

# Verify Nginx is running
if pgrep nginx > /dev/null
then
    echo "Nginx is running"
else
    echo "Nginx is not running"
    exit 1
fi
