#!/usr/bin/env bash
# A script that reloads Gunicorn in a graceful way

# Find the Gunicorn master process ID
GUNICORN_PID=$(pgrep -f "gunicorn.*master")

# Send the HUP signal to the Gunicorn master process to reload gracefully
if [ -n "$GUNICORN_PID" ]; then
	kill -HUP "$GUNICORN_PID"
	echo "Gunicorn has been gracefully reloaded."
else
	echo "Gunicorn master process not found."
fi
